In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DIR)

Project root: c:\Users\Abhijith Shetty\Downloads\E-Learning-Behavior-Segmentation
Raw data: c:\Users\Abhijith Shetty\Downloads\E-Learning-Behavior-Segmentation\data\raw

In [ ]:
student_info = pd.read_csv(RAW_DIR / "studentInfo.csv")
vle = pd.read_csv(RAW_DIR / "vle.csv")
assessments = pd.read_csv(RAW_DIR / "assessments.csv")
student_assessment = pd.read_csv(RAW_DIR / "studentAssessment.csv")
courses = pd.read_csv(RAW_DIR / "courses.csv")
student_registration = pd.read_csv(RAW_DIR / "studentRegistration.csv")
datasets = {
    "studentInfo": student_info,
    "vle": vle,
    "assessments": assessments,
    "studentAssessment": student_assessment,
    "courses": courses,
    "studentRegistration": student_registration
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

In [5]:
for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 50)
    print(df.columns.tolist())

studentInfo
--------------------------------------------------
['code_module', 'code_presentation', 'id_student', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'final_result']

vle
--------------------------------------------------
['id_site', 'code_module', 'code_presentation', 'activity_type', 'week_from', 'week_to']

assessments
--------------------------------------------------
['code_module', 'code_presentation', 'id_assessment', 'assessment_type', 'date', 'weight']

studentAssessment
--------------------------------------------------
['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score']

courses
--------------------------------------------------
['code_module', 'code_presentation', 'module_presentation_length']

studentRegistration
--------------------------------------------------
['code_module', 'code_presentation', 'id_student', 'date_registration', 'date_unregistration']

In [12]:
student_info.head()
vle.head()
assessments.head()
student_assessment.head()
student_registration.head()
courses.head()

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240

In [13]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

studentInfo
code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

vle
id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

assessments
code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64

studentAssessment
id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

courses
code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64

studentRegistration
code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64

## Explore studentInfo.csv

In [14]:
student_info.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [15]:
student_info.columns.tolist()

['code_module',
 'code_presentation',
 'id_student',
 'gender',
 'region',
 'highest_education',
 'imd_band',
 'age_band',
 'num_of_prev_attempts',
 'studied_credits',
 'disability',
 'final_result']

In [16]:
student_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  str
 1   code_presentation     32593 non-null  str
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  str
 4   region                32593 non-null  str
 5   highest_education     32593 non-null  str
 6   imd_band              31482 non-null  str
 7   age_band              32593 non-null  str
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  str
 11  final_result          32593 non-null  str
dtypes: int64(3), str(9)
memory usage: 4.8 MB

In [17]:
student_info.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [18]:
student_info["final_result"].value_counts()

final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [19]:
student_info["code_module"].value_counts()

code_module
BBB    7909
FFF    7762
DDD    6272
CCC    4434
EEE    2934
GGG    2534
AAA     748
Name: count, dtype: int64

In [20]:
student_info["code_presentation"].value_counts()

code_presentation
2014J    11260
2013J     8845
2014B     7804
2013B     4684
Name: count, dtype: int64

In [21]:
student_info["id_student"].nunique()

28785

In [22]:
student_info.shape[0]

32593

In [23]:
student_info.groupby("id_student").size().value_counts().sort_index()

1    25247
2     3293
3      221
4       23
5        1
Name: count, dtype: int64

## Explore vle.csv

In [24]:
vle.head()

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN

In [25]:
vle.columns.tolist()

['id_site',
 'code_module',
 'code_presentation',
 'activity_type',
 'week_from',
 'week_to']

In [26]:
vle.info()

<class 'pandas.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_site            6364 non-null   int64
 1   code_module        6364 non-null   str
 2   code_presentation  6364 non-null   str
 3   activity_type      6364 non-null   str
 4   week_from          1121 non-null   float64
 5   week_to            1121 non-null   float64
dtypes: float64(2), int64(1), str(3)
memory usage: 393.3 KB

In [27]:
vle.isnull().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [28]:
vle["activity_type"].value_counts()

activity_type
resource          2660
subpage           1055
oucontent          996
url                886
forumng            194
quiz               127
page               102
oucollaborate       82
questionnaire       61
ouwiki              49
dataplus            28
externalquiz        26
homepage            22
glossary            21
ouelluminate        21
dualpane            20
repeatactivity       5
htmlactivity         4
sharedsubpage        3
folder               2
Name: count, dtype: int64

In [29]:
vle["activity_type"].nunique()

20

In [30]:
vle.groupby("activity_type").size().sort_values(ascending=False)

activity_type
resource          2660
subpage           1055
oucontent          996
url                886
forumng            194
quiz               127
page               102
oucollaborate       82
questionnaire       61
ouwiki              49
dataplus            28
externalquiz        26
homepage            22
glossary            21
ouelluminate        21
dualpane            20
repeatactivity       5
htmlactivity         4
sharedsubpage        3
folder               2
dtype: int64

## Explore assessments.csv

In [31]:
assessments.head()

  code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0

In [32]:
assessments.columns.tolist()

['code_module',
 'code_presentation',
 'id_assessment',
 'assessment_type',
 'date',
 'weight']

In [33]:
assessments.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        206 non-null    str
 1   code_presentation  206 non-null    str
 2   id_assessment      206 non-null    int64
 3   assessment_type    206 non-null    str
 4   date               195 non-null    float64
 5   weight             206 non-null    float64
dtypes: float64(2), int64(1), str(3)
memory usage: 12.0 KB

In [34]:
assessments.isnull().sum()

code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64

In [35]:
assessments["assessment_type"].value_counts()

assessment_type
TMA     106
CMA      76
Exam     24
Name: count, dtype: int64

In [36]:
assessments[
    [
        "code_module",
        "code_presentation",
        "id_assessment",
        "assessment_type",
        "date",
        "weight"
    ]
].head(20)

   code_module code_presentation  id_assessment assessment_type   date  weight
0          AAA             2013J           1752             TMA   19.0    10.0
1          AAA             2013J           1753             TMA   54.0    20.0
2          AAA             2013J           1754             TMA  117.0    20.0
3          AAA             2013J           1755             TMA  166.0    20.0
4          AAA             2013J           1756             TMA  215.0    30.0
5          AAA             2013J           1757            Exam    NaN   100.0
6          AAA             2014J           1758             TMA   19.0    10.0
7          AAA             2014J           1759             TMA   54.0    20.0
8          AAA             2014J           1760             TMA  117.0    20.0
9          AAA             2014J           1761             TMA  166.0    20.0
10         AAA             2014J           1762             TMA  215.0    30.0
11         AAA             2014J           1763            Exam    NaN   100.0
12         BBB             2013B          14991             CMA   54.0     1.0
13         BBB             2013B          14992             CMA   89.0     1.0
14         BBB             2013B          14993             CMA  124.0     1.0
15         BBB             2013B          14994             CMA  159.0     1.0
16         BBB             2013B          14995             CMA  187.0     1.0
17         BBB             2013B          14984             TMA   19.0     5.0
18         BBB             2013B          14985             TMA   47.0    18.0
19         BBB             2013B          14986             TMA   89.0    18.0

## Explore studentAssessment.csv

In [37]:
student_assessment.head()

   id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18          0   78.0
1           1752       28400              22          0   70.0
2           1752       31604              17          0   72.0
3           1752       32885              26          0   69.0
4           1752       38053              19          0   79.0

In [38]:
student_assessment.columns.tolist()

['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score']

In [39]:
student_assessment.info()

<class 'pandas.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_assessment   173912 non-null  int64
 1   id_student      173912 non-null  int64
 2   date_submitted  173912 non-null  int64
 3   is_banked       173912 non-null  int64
 4   score           173739 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 6.6 MB

In [40]:
student_assessment.isnull().sum()

id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

In [41]:
student_assessment[
    [
        "id_assessment",
        "id_student",
        "date_submitted",
        "is_banked",
        "score"
    ]
].head(20)

    id_assessment  id_student  date_submitted  is_banked  score
0            1752       11391              18          0   78.0
1            1752       28400              22          0   70.0
2            1752       31604              17          0   72.0
3            1752       32885              26          0   69.0
4            1752       38053              19          0   79.0
5            1752       45462              20          0   70.0
6            1752       45642              18          0   72.0
7            1752       52130              19          0   72.0
8            1752       53025               9          0   71.0
9            1752       57506              18          0   68.0
10           1752       58873              19          0   73.0
11           1752       59185              18          0   67.0
12           1752       62155              17          0   73.0
13           1752       63400              19          0   83.0
14           1752       65002              17          0   66.0
15           1752       70464              19          0   59.0
16           1752       71361              19          0   82.0
17           1752       74372              22          0   60.0
18           1752       75091              18          0   67.0
19           1752       77367              18          0   73.0

In [42]:
student_assessment["score"].describe()

count    173739.000000
mean         75.799573
std          18.798107
min           0.000000
25%          65.000000
50%          80.000000
75%          90.000000
max         100.000000
Name: score, dtype: float64

In [43]:
assessment_data = student_assessment.merge(
    assessments,
    on="id_assessment",
    how="left"
)

In [44]:
assessment_data.head()

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight
0,1752,11391,18,0,78.0,AAA,2013J,TMA,19.0,10.0
1,1752,28400,22,0,70.0,AAA,2013J,TMA,19.0,10.0
2,1752,31604,17,0,72.0,AAA,2013J,TMA,19.0,10.0
3,1752,32885,26,0,69.0,AAA,2013J,TMA,19.0,10.0
4,1752,38053,19,0,79.0,AAA,2013J,TMA,19.0,10.0

In [45]:
assessment_data[
    [
        "id_student",
        "id_assessment",
        "assessment_type",
        "date",
        "date_submitted",
        "score"
    ]
].head(20)

    id_student  id_assessment assessment_type  date  date_submitted  score
0        11391           1752             TMA  19.0              18   78.0
1        28400           1752             TMA  19.0              22   70.0
2        31604           1752             TMA  19.0              17   72.0
3        32885           1752             TMA  19.0              26   69.0
4        38053           1752             TMA  19.0              19   79.0
5        45462           1752             TMA  19.0              20   70.0
6        45642           1752             TMA  19.0              18   72.0
7        52130           1752             TMA  19.0              19   72.0
8        53025           1752             TMA  19.0               9   71.0
9        57506           1752             TMA  19.0              18   68.0
10       58873           1752             TMA  19.0              19   73.0
11       59185           1752             TMA  19.0              18   67.0
12       62155           1752             TMA  19.0              17   73.0
13       63400           1752             TMA  19.0              19   83.0
14       65002           1752             TMA  19.0              17   66.0
15       70464           1752             TMA  19.0              19   59.0
16       71361           1752             TMA  19.0              19   82.0
17       74372           1752             TMA  19.0              22   60.0
18       75091           1752             TMA  19.0              18   67.0
19       77367           1752             TMA  19.0              18   73.0

In [46]:
assessment_data["submission_difference"] = (
    assessment_data["date_submitted"] -
    assessment_data["date"]
)

In [47]:
assessment_data[
    [
        "id_student",
        "date",
        "date_submitted",
        "submission_difference"
    ]
].head(20)

    id_student  date  date_submitted  submission_difference
0        11391  19.0              18                   -1.0
1        28400  19.0              22                    3.0
2        31604  19.0              17                   -2.0
3        32885  19.0              26                    7.0
4        38053  19.0              19                    0.0
5        45462  19.0              20                    1.0
6        45642  19.0              18                   -1.0
7        52130  19.0              19                    0.0
8        53025  19.0               9                  -10.0
9        57506  19.0              18                   -1.0
10       58873  19.0              19                    0.0
11       59185  19.0              18                   -1.0
12       62155  19.0              17                   -2.0
13       63400  19.0              19                    0.0
14       65002  19.0              17                   -2.0
15       70464  19.0              19                    0.0
16       71361  19.0              19                    0.0
17       74372  19.0              22                    3.0
18       75091  19.0              18                   -1.0
19       77367  19.0              18                   -1.0

In [48]:
student_assessment.groupby("id_student")["id_assessment"].count().describe()

count    23369.000000
mean         7.441996
std          4.223937
min          1.000000
25%          4.000000
50%          7.000000
75%         11.000000
max         28.000000
Name: id_assessment, dtype: float64

In [49]:
student_assessment.groupby("id_student")["id_assessment"].count().head(20)

id_student
6516      5
8462      7
11391     5
23629     4
23698     9
23798    11
24186     8
24213     7
24391     9
24734     5
25107    11
25150     4
25261     1
25572     2
25997     2
26023     9
26192     5
26211    12
26247     1
26315     5
Name: id_assessment, dtype: int64

## Explore studentVle.csv

In [50]:
student_vle_sample = pd.read_csv(
    RAW_DIR / "studentVle.csv",
    nrows=20000
)

student_vle_sample.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [51]:
student_vle_sample.shape

(20000, 6)

In [52]:
student_vle_sample.columns.tolist()

['code_module',
 'code_presentation',
 'id_student',
 'id_site',
 'date',
 'sum_click']

In [53]:
student_vle_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        20000 non-null  str
 1   code_presentation  20000 non-null  str
 2   id_student         20000 non-null  int64
 3   id_site            20000 non-null  int64
 4   date               20000 non-null  int64
 5   sum_click          20000 non-null  int64
dtypes: int64(4), str(2)
memory usage: 1.1 MB

In [54]:
student_vle_sample.describe()

         id_student        id_site          date     sum_click
count  2.000000e+04   20000.000000  20000.000000  20000.000000
mean   1.028470e+06  546730.821550     -2.008850      4.288850
std    9.792093e+05     119.768549      5.418601      5.573892
min    1.139100e+04  546614.000000    -10.000000      1.000000
25%    2.274990e+05  546652.000000     -7.000000      1.000000
50%    3.908900e+05  546667.000000     -2.000000      2.000000
75%    2.122180e+06  546871.000000      3.000000      5.000000
max    2.698257e+06  547067.000000      7.000000    144.000000

In [55]:
student_vle_sample.head(20)

   code_module code_presentation  id_student  id_site  date  sum_click
0          AAA             2013J       28400   546652   -10          4
1          AAA             2013J       28400   546652   -10          1
2          AAA             2013J       28400   546652   -10          1
3          AAA             2013J       28400   546614   -10         11
4          AAA             2013J       28400   546714   -10          1
5          AAA             2013J       28400   546652   -10          8
6          AAA             2013J       28400   546876   -10          2
7          AAA             2013J       28400   546688   -10         15
8          AAA             2013J       28400   546662   -10         17
9          AAA             2013J       28400   546890   -10          1
10         AAA             2013J       28400   547011   -10          1
11         AAA             2013J       28400   547013   -10          1
12         AAA             2013J       28400   546871   -10          3
13         AAA             2013J       28400   546879   -10          4
14         AAA             2013J       30268   546652   -10          3
15         AAA             2013J       30268   546662   -10          2
16         AAA             2013J       30268   546614   -10          3
17         AAA             2013J       30268   546652   -10          2
18         AAA             2013J       31604   546672   -10          1
19         AAA             2013J       31604   547013   -10          5

In [56]:
student_vle_sample["id_student"].nunique()

371

In [57]:
student_vle_sample["id_site"].nunique()

121

In [58]:
student_vle_sample["date"].min(), student_vle_sample["date"].max()

(np.int64(-10), np.int64(7))

In [59]:
sample_student = student_vle_sample["id_student"].iloc[0]

sample_student

np.int64(28400)

In [60]:
student_vle_sample[
    student_vle_sample["id_student"] == sample_student
].head(30)

     code_module code_presentation  id_student  id_site  date  sum_click
0            AAA             2013J       28400   546652   -10          4
1            AAA             2013J       28400   546652   -10          1
2            AAA             2013J       28400   546652   -10          1
3            AAA             2013J       28400   546614   -10         11
4            AAA             2013J       28400   546714   -10          1
5            AAA             2013J       28400   546652   -10          8
6            AAA             2013J       28400   546876   -10          2
7            AAA             2013J       28400   546688   -10         15
8            AAA             2013J       28400   546662   -10         17
9            AAA             2013J       28400   546890   -10          1
10           AAA             2013J       28400   547011   -10          1
11           AAA             2013J       28400   547013   -10          1
12           AAA             2013J       28400   546871   -10          3
13           AAA             2013J       28400   546879   -10          4
3909         AAA             2013J       28400   546652    -8          3
3910         AAA             2013J       28400   546614    -8          4
3911         AAA             2013J       28400   546681    -8          1
3912         AAA             2013J       28400   546652    -8          1
5276         AAA             2013J       28400   546681    -7          8
5277         AAA             2013J       28400   546732    -7          2
5278         AAA             2013J       28400   546986    -7          1
5279         AAA             2013J       28400   546662    -7          3
5280         AAA             2013J       28400   546719    -7          8
5281         AAA             2013J       28400   546731    -7          2
5282         AAA             2013J       28400   546871    -7          1
5283         AAA             2013J       28400   546652    -7         13
5284         AAA             2013J       28400   546883    -7          3
5285         AAA             2013J       28400   547009    -7          1
5286         AAA             2013J       28400   546652    -7          3
5287         AAA             2013J       28400   546879    -7          3

In [61]:
student_vle_sample[
    student_vle_sample["id_student"] == sample_student
]["sum_click"].sum()

np.int64(397)

In [62]:
student_vle_sample[
    student_vle_sample["id_student"] == sample_student
]["date"].nunique()

13

## Merge studentVle with VLE resource information

In [63]:
sample_activity = student_vle_sample.merge(
    vle,
    on=[
        "code_module",
        "code_presentation",
        "id_site"
    ],
    how="left"
)

sample_activity.head()

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,week_from,week_to
0,AAA,2013J,28400,546652,-10,4,forumng,NaN,NaN
1,AAA,2013J,28400,546652,-10,1,forumng,NaN,NaN
2,AAA,2013J,28400,546652,-10,1,forumng,NaN,NaN
3,AAA,2013J,28400,546614,-10,11,homepage,NaN,NaN
4,AAA,2013J,28400,546714,-10,1,oucontent,NaN,NaN

In [64]:
sample_activity[
    [
        "id_student",
        "date",
        "sum_click",
        "activity_type"
    ]
].head(30)

    id_student  date  sum_click activity_type
0        28400   -10          4       forumng
1        28400   -10          1       forumng
2        28400   -10          1       forumng
3        28400   -10         11      homepage
4        28400   -10          1     oucontent
5        28400   -10          8       forumng
6        28400   -10          2       subpage
7        28400   -10         15     oucontent
8        28400   -10         17     oucontent
9        28400   -10          1           url
10       28400   -10          1      resource
11       28400   -10          1      resource
12       28400   -10          3       subpage
13       28400   -10          4       subpage
14       30268   -10          3       forumng
15       30268   -10          2     oucontent
16       30268   -10          3      homepage
17       30268   -10          2       forumng
18       31604   -10          1     oucontent
19       31604   -10          5      resource
20       31604   -10          3       subpage
21       31604   -10         11      homepage
22       31604   -10          1      glossary
23       31604   -10         19     oucontent
24       31604   -10          9       subpage
25       31604   -10          4     oucontent
26       31604   -10          7     oucontent
27       32885   -10          5     oucontent
28       32885   -10          1      resource
29       32885   -10          1       forumng

In [65]:
sample_activity["activity_type"].isnull().sum()

np.int64(0)

In [66]:
sample_activity["activity_type"].value_counts()

activity_type
oucontent        5984
forumng          5614
homepage         2861
subpage          2765
resource         1548
url               983
oucollaborate     113
dataplus           79
glossary           53
Name: count, dtype: int64

## Basic Student Behaviour Aggregation

In [67]:
basic_activity = (
    student_vle_sample
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation"
        ]
    )
    .agg(
        total_clicks=("sum_click", "sum"),
        active_days=("date", "nunique"),
        first_activity=("date", "min"),
        last_activity=("date", "max"),
        unique_resources=("id_site", "nunique")
    )
    .reset_index()
)

basic_activity.head()

,id_student,code_module,code_presentation,total_clicks,active_days,first_activity,last_activity,unique_resources
0,11391,AAA,2013J,281,5,-5,6,19
1,28400,AAA,2013J,397,13,-10,7,27
2,30268,AAA,2013J,209,9,-10,6,20
3,31604,AAA,2013J,220,7,-10,7,21
4,32885,AAA,2013J,356,13,-10,6,27

In [68]:
basic_activity.shape

(371, 8)

In [69]:
basic_activity["activity_span"] = (
    basic_activity["last_activity"]
    - basic_activity["first_activity"]
)

basic_activity.head()

,id_student,code_module,code_presentation,total_clicks,active_days,first_activity,last_activity,unique_resources,activity_span
0,11391,AAA,2013J,281,5,-5,6,19,11
1,28400,AAA,2013J,397,13,-10,7,27,17
2,30268,AAA,2013J,209,9,-10,6,20,16
3,31604,AAA,2013J,220,7,-10,7,21,17
4,32885,AAA,2013J,356,13,-10,6,27,16

In [70]:
student_vle_sample["week"] = (
    student_vle_sample["date"] // 7
)

In [71]:
active_weeks = (
    student_vle_sample
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation"
        ]
    )["week"]
    .nunique()
    .reset_index(name="active_weeks")
)

active_weeks.head()

   id_student code_module code_presentation  active_weeks
0       11391         AAA             2013J             2
1       28400         AAA             2013J             4
2       30268         AAA             2013J             3
3       31604         AAA             2013J             4
4       32885         AAA             2013J             3

In [72]:
basic_activity = basic_activity.merge(
    active_weeks,
    on=[
        "id_student",
        "code_module",
        "code_presentation"
    ],
    how="left"
)

basic_activity.head()

,id_student,code_module,code_presentation,total_clicks,active_days,first_activity,last_activity,unique_resources,activity_span,active_weeks
0,11391,AAA,2013J,281,5,-5,6,19,11,2
1,28400,AAA,2013J,397,13,-10,7,27,17,4
2,30268,AAA,2013J,209,9,-10,6,20,16,3
3,31604,AAA,2013J,220,7,-10,7,21,17,4
4,32885,AAA,2013J,356,13,-10,6,27,16,3

In [73]:
student_vle = pd.read_csv(
    RAW_DIR / "studentVle.csv",
    dtype={
        "code_module": "category",
        "code_presentation": "category",
        "id_student": "int32",
        "id_site": "int32",
        "date": "int16",
        "sum_click": "int32"
    }
)

print("Loaded successfully")

Loaded successfully

In [74]:
student_vle.shape

(10655280, 6)

In [75]:
student_vle.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        category
 1   code_presentation  category
 2   id_student         int32
 3   id_site            int32
 4   date               int16
 5   sum_click          int32
dtypes: category(2), int16(1), int32(3)
memory usage: 162.6 MB

In [76]:
print("Rows:", len(student_vle))
print("Unique students:", student_vle["id_student"].nunique())
print("Unique resources:", student_vle["id_site"].nunique())
print("Minimum date:", student_vle["date"].min())
print("Maximum date:", student_vle["date"].max())
print("Total clicks:", student_vle["sum_click"].sum())

Rows: 10655280
Unique students: 26074
Unique resources: 6268
Minimum date: -25
Maximum date: 269
Total clicks: 39605099

In [77]:
student_vle.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [78]:
student_vle["week"] = student_vle["date"] // 7

In [79]:
student_activity = (
    student_vle
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation"
        ],
        observed=True
    )
    .agg(
        total_clicks=("sum_click", "sum"),
        active_days=("date", "nunique"),
        active_weeks=("week", "nunique"),
        first_activity=("date", "min"),
        last_activity=("date", "max"),
        unique_resources=("id_site", "nunique")
    )
    .reset_index()
)

student_activity.head()

,id_student,code_module,code_presentation,total_clicks,active_days,active_weeks,first_activity,last_activity,unique_resources
0,6516,AAA,2014J,2791,159,39,-23,269,84
1,8462,DDD,2013J,646,56,17,-6,118,125
2,8462,DDD,2014J,10,1,1,10,10,3
3,11391,AAA,2013J,934,40,27,-5,253,55
4,23629,BBB,2013B,161,16,11,-6,87,11

In [80]:
student_activity["activity_span"] = (
    student_activity["last_activity"]
    - student_activity["first_activity"]
)

In [81]:
student_activity.shape

(29228, 10)

In [82]:
student_activity.describe()

,id_student,total_clicks,active_days,active_weeks,first_activity,last_activity,unique_resources,activity_span
count,2.922800e+04,29228.000000,29228.000000,29228.000000,29228.000000,29228.000000,29228.000000,29228.000000
mean,7.083367e+05,1355.039654,61.862563,21.453093,-8.224374,177.294204,67.075955,185.518578
std,5.517362e+05,1733.546045,54.027412,12.458364,13.113730,90.146308,54.953382,92.447016
min,6.516000e+03,1.000000,1.000000,1.000000,-25.000000,-25.000000,1.000000,0.000000
25%,5.075768e+05,260.750000,18.000000,10.000000,-17.000000,96.000000,27.000000,104.000000
50%,5.898280e+05,739.500000,47.000000,23.000000,-10.000000,228.000000,51.000000,234.000000
75%,6.437068e+05,1770.000000,92.000000,33.000000,-4.000000,242.000000,93.000000,256.000000
max,2.698588e+06,24139.000000,286.000000,43.000000,238.000000,269.000000,413.000000,293.000000

In [83]:
activity_with_type = student_vle.merge(
    vle[
        [
            "code_module",
            "code_presentation",
            "id_site",
            "activity_type"
        ]
    ],
    on=[
        "code_module",
        "code_presentation",
        "id_site"
    ],
    how="left"
)

In [84]:
activity_with_type[
    [
        "id_student",
        "date",
        "sum_click",
        "activity_type"
    ]
].head()

   id_student  date  sum_click activity_type
0       28400   -10          4       forumng
1       28400   -10          1       forumng
2       28400   -10          1       forumng
3       28400   -10         11      homepage
4       28400   -10          1     oucontent

In [85]:
activity_with_type["activity_type"].value_counts()

activity_type
forumng           2408457
oucontent         1963782
subpage           1949898
homepage          1735226
quiz               914573
resource           813185
url                407716
ouwiki             178165
oucollaborate       65793
externalquiz        50910
page                47549
questionnaire       44905
ouelluminate        22360
glossary            17435
dataplus            13506
dualpane            10153
htmlactivity         6835
folder               4678
sharedsubpage         148
repeatactivity          6
Name: count, dtype: int64

In [86]:
activity_type_summary = (
    activity_with_type
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "activity_type"
        ],
        observed=True
    )["sum_click"]
    .sum()
    .reset_index(name="activity_clicks")
)

activity_type_summary.head()

   id_student code_module code_presentation activity_type  activity_clicks
0        6516         AAA             2014J      dataplus               21
1        6516         AAA             2014J       forumng              451
2        6516         AAA             2014J      homepage              497
3        6516         AAA             2014J     oucontent             1505
4        6516         AAA             2014J      resource               31

In [87]:
preferred_activity = (
    activity_type_summary
    .sort_values(
        "activity_clicks",
        ascending=False
    )
    .drop_duplicates(
        subset=[
            "id_student",
            "code_module",
            "code_presentation"
        ]
    )
)

In [88]:
preferred_activity = preferred_activity[
    [
        "id_student",
        "code_module",
        "code_presentation",
        "activity_type"
    ]
].rename(
    columns={
        "activity_type": "preferred_activity"
    }
)

preferred_activity.head()

        id_student code_module code_presentation preferred_activity
125648      593694         BBB             2013J            forumng
148234      611417         CCC             2014J               quiz
75604       540184         BBB             2013B            forumng
90281       556898         BBB             2013B            forumng
210707      695232         CCC             2014J               quiz

In [89]:
student_activity = student_activity.merge(
    preferred_activity,
    on=[
        "id_student",
        "code_module",
        "code_presentation"
    ],
    how="left"
)

student_activity.head()

,id_student,code_module,code_presentation,total_clicks,active_days,active_weeks,first_activity,last_activity,unique_resources,activity_span,preferred_activity
0,6516,AAA,2014J,2791,159,39,-23,269,84,292,oucontent
1,8462,DDD,2013J,646,56,17,-6,118,125,124,subpage
2,8462,DDD,2014J,10,1,1,10,10,3,0,homepage
3,11391,AAA,2013J,934,40,27,-5,253,55,258,oucontent
4,23629,BBB,2013B,161,16,11,-6,87,11,93,forumng

In [90]:
student_activity.to_csv(
    PROCESSED_DIR / "student_activity_summary.csv",
    index=False
)